# Generated by Django 3.1.2 on 2020-11-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='projectname',
        ),
    ]
