# Generated by Django 3.1.2 on 2020-11-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201102_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='creativity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
